---
- hosts: frontend
  become: yes
  become_method: sudo
  remote_user: "ubuntu"
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      become: true
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3-minimal)
      changed_when: false
    - setup: # aka gather_facts
  vars:
    # Cloudwatch Logs Role configuration
    logs:
      - file: /var/log/messages
        group_name: "system_logs"
  roles:
    - common
    - florianutz.Ubuntu1604-CIS
    # - dharrisio.aws-cloudwatch-logs-agent
