---
- hosts: localhost
  become: yes
  become_method: sudo
  remote_user: "ubuntu"
  gather_facts: false
  vars:
    # Cloudwatch Logs Role configuration
    logs:
      - file: /var/log/messages
        group_name: "system_logs"
  roles:
    - common
    - Ubuntu1604-CIS
    # - dharrisio.aws-cloudwatch-logs-agent
